// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIqYJ0zL347oCD6SyH2Egy1SiUHeHnz4A',
    appId: '1:750016309584:web:82f14dc1bc02671f246455',
    messagingSenderId: '750016309584',
    projectId: 'shadisphere-11fa5',
    authDomain: 'shadisphere-11fa5.firebaseapp.com',
    databaseURL: 'https://shadisphere-11fa5-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'shadisphere-11fa5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCU-edIPKIfdo4KLfPZfYz8XHYSztXQjJI',
    appId: '1:750016309584:android:852f7ce4be94db17246455',
    messagingSenderId: '750016309584',
    projectId: 'shadisphere-11fa5',
    databaseURL: 'https://shadisphere-11fa5-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'shadisphere-11fa5.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIqYJ0zL347oCD6SyH2Egy1SiUHeHnz4A',
    appId: '1:750016309584:web:4e7412a1f269099d246455',
    messagingSenderId: '750016309584',
    projectId: 'shadisphere-11fa5',
    authDomain: 'shadisphere-11fa5.firebaseapp.com',
    databaseURL: 'https://shadisphere-11fa5-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'shadisphere-11fa5.firebasestorage.app',
  );
}
